services:
  - type: web
    name: ai-doctor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker src.gradio_app_advanced:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: GEMINI_API_KEY
        value: ""
      - key: GROQ_API_KEY
        value: ""
